### ISSUE TITLE
LogUtility.MaskSensitiveData is not thread safe

### ISSUE THREAD

**Issue by wrightsonm** [CyberSource/cybersource-rest-client-dotnet#123]
(Also raised on NetStandard repository) - [Dot Net Standard Issue 22](https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/issues/22)

We have just pulled in the latest changes that include the new logging with MaskSensitiveData options, and quickly identified a concurrency issue when deploying to production.

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
at AuthenticationSdk.util.LogUtility.MaskSensitiveData(String str)
at CyberSource.Api.KeyGenerationApi.GeneratePublicKeyWithHttpInfo(String format, GeneratePublicKeyRequest generatePublicKeyRequest)
at CyberSource.Api.KeyGenerationApi.GeneratePublicKey(String format, GeneratePublicKeyRequest generatePublicKeyRequest)

Specifically we deployed the netFramework version, but am discussing here as AuthenticationSdk for netFramework is closed source, and the NetStandard version is open source & can be seen to be non-thread safe here:

[AuthenticationSdk/util/LogUtility.cs](https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/blob/8e5409a9a254f53bccda4439dffe69c48b507c2a/cybersource-rest-auth-netstandard/AuthenticationSdk/AuthenticationSdk/util/LogUtility.cs)

Tagging developers to flag this issue: @gnongsie @chsriniv9

**Comment by wrightsonm** [comment]
See PR https://github.com/CyberSource/cybersource-rest-client-dotnetstandard/pull/23
