### ISSUE TITLE
SearchReports broken, gives 404 when calling

### ISSUE THREAD

**Issue by xantari** [CyberSource/cybersource-rest-client-dotnet#40]
Here is my code:

var result = reportApiSearch.SearchReports(reportDate, reportDate, "reportTimeFrame");

![image](https://user-images.githubusercontent.com/6610039/60441783-5f45d300-9bdd-11e9-97b9-f44f66d26e46.png)

Stack Trace:
```
   at CyberSource.Api.ReportsApi.SearchReportsWithHttpInfo(Nullable`1 startTime, Nullable`1 endTime, String timeQueryType, String organizationId, String reportMimeType, String reportFrequency, String reportName, Nullable`1 reportDefinitionId, String reportStatus)
   at CyberSource.Api.ReportsApi.SearchReports(Nullable`1 startTime, Nullable`1 endTime, String timeQueryType, String organizationId, String reportMimeType, String reportFrequency, String reportName, Nullable`1 reportDefinitionId, String reportStatus)
   at ARRT.Payments.Services.Vendors.CyberSource.CyberSourceGateway.<DownloadReport>d__1.MoveNext() in C:\TFS\ARRT.All.Projects\ARRT.Payments.Services\Vendors\CyberSource\CyberSourceGateway.cs:line 61
```

**Comment by xantari** [comment]
It appears that you get a 404 when organizationId is passed as null. But it isn't required according to the method. When I pass in my merchantId however I get 0 data, for a several day date range even though there are reports in that date range. Seems this library is broken here as well.

**Comment by xantari** [comment]
I debugged this further using fiddler and found that this .NET library is not mapping the result data back to the caller. The fiddler response from the API is getting the data, but it's another bug in the API that is similar to #36 where the response data isn't getting mapped back.

**Comment by xantari** [comment]
So there are two issues with SearchReports():

1. When you don't pass in organizationId you get a 404. Even though the parameter is not marked as required in the REST client.
2. When you do pass in all of the required parameters it fails due to issue #47. I have provided the code fix for this issue in #47.

**Comment by gnongsie** [comment]
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet (**v0.0.0.10**) and check again.

**Comment by snavinch** [comment]
Closing this issue as this has been addressed
