### ISSUE TITLE
"Hello World" sample throws NullReferenceException in the REST client

### ISSUE THREAD

**Issue by brutaldev** [CyberSource/cybersource-rest-client-dotnet#73]
The same code on https://developer.cybersource.com/hello-world.html simply fails with a `NullReferenceException` when the `CreatePayment` call gets made. Configuration is setup to use `HTTP_SIGNATURE` on the sandbox.

Here is the stack trace where it throws the exception:
```
   at CyberSource.Client.ApiClient.CallAuthenticationHeaders(String requestType, String requestTarget, String requestJsonData)
   at CyberSource.Client.ApiClient.PrepareRequest(String path, Method method, Dictionary`2 queryParams, Object postBody, Dictionary`2 headerParams, Dictionary`2 formParams, Dictionary`2 fileParams, Dictionary`2 pathParams, String contentType)
   at CyberSource.Client.ApiClient.CallApi(String path, Method method, Dictionary`2 queryParams, Object postBody, Dictionary`2 headerParams, Dictionary`2 formParams, Dictionary`2 fileParams, Dictionary`2 pathParams, String contentType)
   at CyberSource.Api.PaymentsApi.CreatePaymentWithHttpInfo(CreatePaymentRequest createPaymentRequest)
   at CyberSource.Api.PaymentsApi.CreatePayment(CreatePaymentRequest createPaymentRequest)
```

**Comment by ssethumavisa** [comment]
We are checking the same, will get back to you shortly

**Comment by flyingahh** [comment]
I get this same issue calling any API method. Also using HTTP_SIGNATURE on the sandbox.

**Comment by flyingahh** [comment]
> I get this same issue calling any API method. Also using HTTP_SIGNATURE on the sandbox.

It turns out I did not use the right secret key. The rest client seems to function correctly now. However, it would be nice if the exception could indicate an incorrect secret key. Thanks.

**Comment by xantari** [comment]
@flyingahh  You should close this issue since it is solved.

**Comment by snavinch** [comment]
Thank you for the suggestion, We will communicate this to the relevant team.
I'll be closing this now, Feel free to contact us for any further queries
